language: android
dist: trusty
android:
  components:
         - build-tools-29.0.2  # The BuildTools version used by your project
         - android-29 # The SDK version used to compile your project
