language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2  # The BuildTools version used by your project
    - android-29 # The SDK version used to compile your project
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean
  - ./gradlew assembleDebug

branches:
  only:
    - master


